In [6]:
#Creating arrays
import numpy as np
a=np.array([0,1,2,3,4])
print(a)
print(np.arange(10))
%timeit a


[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
51.1 ns ± 3.62 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [8]:
L=range(1000)
%timeit [i**2 for i in L]

1.12 ms ± 338 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
a=np.arange(1000)
%timeit a**2

4.11 µs ± 96.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
#1-D array is called vector
a=np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [10]:
a.ndim

1

In [11]:
a.shape

(5,)

In [13]:
#2-D array is called matrix
b=np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
b.ndim

2

In [15]:
b.shape

(2, 3)

In [16]:
len(b)

2

In [22]:
#N-D array is called Tensor
C=np.array([[[0,1,2],[3,4,5]],[[0,1,2],[3,4,5]]])
C

array([[[0, 1, 2],
        [3, 4, 5]],

       [[0, 1, 2],
        [3, 4, 5]]])

In [23]:
C.ndim

3

In [24]:
C.shape

(2, 2, 3)

In [25]:
D=np.arange(0,10,2)
D

array([0, 2, 4, 6, 8])

In [107]:
E=np.linspace(0,1,4)
E

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [28]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [108]:
#Identity matrix
# C=np.eye(2,dtype=int)
C=np.eye(3,3,dtype=int)
C

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [34]:
# C=np.eye(2,dtype=int)
C=np.diag([1,2,3,4,5])
C

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [37]:
#Rand-uniform random variable
a=np.random.rand(4)
a

array([0.9282046 , 0.64475593, 0.73124382, 0.6623845 ])

In [38]:
#Randn-standard random variable
a=np.random.randn(4)
a

array([ 0.30737583,  0.16271299, -1.33610037,  0.36445514])

In [39]:
#Datatype
a.dtype

dtype('float64')

In [42]:
a=np.arange(10,dtype='int')
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a=np.array([1+2j,2+4j])
a.dtype

dtype('complex128')

In [44]:
a=np.array([True,False,True,False])
a.dtype

dtype('bool')

In [48]:
#Obtaining value
a=np.diag([1,2,3])
print(a[0,0])

1


In [50]:
#Assigning value to (2,1)
a[2,1]=5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [87]:
#Slicing
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
a[0:8:2]

array([0, 2, 4, 6])

In [89]:
a[5:]=7
a

array([0, 1, 2, 3, 4, 7, 7, 7, 7, 7])

In [90]:
#Views
b=np.arange(5)
a[5:]=b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [91]:
a=np.arange(10)
c=a[::2]


In [92]:
np.shares_memory(a,c)

True

In [94]:
c[0]=10
c

array([10,  2,  4,  6,  8])

In [95]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [96]:
a=np.arange(10)

In [97]:
#Copies
b=a[:5:].copy()

In [98]:
np.shares_memory(a,b)

False

In [99]:
b[0]=10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Masking
a=np.random.randint(0,20,15)
a

In [100]:
mask=(a%2==0)

In [101]:
extract_from_a=a[mask]
extract_from_a

array([0, 2, 4, 6, 8])

In [103]:
a[mask]=-1
a

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

In [104]:
#Fancy Indexing
#Indexing with an array of integers
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [105]:
a[[0,2,4,2,1,0]]

array([ 0, 20, 40, 20, 10,  0])

In [106]:
a[[4,6]]=555
a

array([  0,  10,  20,  30, 555,  50, 555,  70,  80,  90])